var HttpCodes = {
    HTTP_OK: 200,
    HTTP_CREATED: 201,
    HTTP_NOT_FOUND: 404,
    HTTP_INTERNAL_ERROR: 500,
    HTTP_CONFLICT: 409,
    HTTP_BAD_REQUEST: 400,
    HTTP_UNAUTHORIZED: 401
};

module.exports = HttpCodes;